/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'org.openassociation.agent'

export { $nsid }

/** A functional structure, formal or informal, which can include people and/or other organizations, and has its own agency.  Something called a group is an Organization in Valueflows if it has agency as the group. */
type Main = {
  $type: 'org.openassociation.agent'

  /**
   * The type of agent.
   */
  agentType?: 'person' | 'organization' | 'ecologicalAgent'

  /**
   * The main place an agent is located, often an address where activities occur and mail can be sent.
   */
  primaryLocation?: Location

  /**
   * The uri to an image relevant to the entity, such as a logo, avatar, photo, diagram, etc.
   */
  image?: l.UriString

  /**
   * An informal or formal textual identifier for an object. Does not imply uniqueness.
   */
  name?: string

  /**
   * Any useful textual information related to the item.
   */
  note?: string

  /**
   * References one or more uri's for a concept in a common taxonomy or other classification scheme for purposes of categorization or grouping; or it can be one or more string classifications such as tags.
   */
  classifiedAs?: string[]
}

export type { Main }

/** A functional structure, formal or informal, which can include people and/or other organizations, and has its own agency.  Something called a group is an Organization in Valueflows if it has agency as the group. */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    agentType: l.optional(
      l.enum(['person', 'organization', 'ecologicalAgent']),
    ),
    primaryLocation: l.optional(l.ref<Location>((() => location) as any)),
    image: l.optional(l.string({ format: 'uri' })),
    name: l.optional(l.string({ maxGraphemes: 640 })),
    note: l.optional(l.string({ maxGraphemes: 10000 })),
    classifiedAs: l.optional(l.array(l.string())),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

type Location = {
  $type?: 'org.openassociation.agent#location'

  /**
   * WGS84 latitude (decimal degrees).
   */
  lat?: string

  /**
   * WGS84 longitude (decimal degrees).
   */
  long?: string

  /**
   * WGS84 altitude (decimal meters above the local reference ellipsoid).
   */
  alt?: string

  /**
   * A textual address that can be mapped using mapping software.
   */
  mappableAddress?: string

  /**
   * An informal or formal textual identifier for the location.
   */
  name?: string
}

export type { Location }

const location = l.typedObject<Location>(
  $nsid,
  'location',
  l.object({
    lat: l.optional(l.string()),
    long: l.optional(l.string()),
    alt: l.optional(l.string()),
    mappableAddress: l.optional(l.string()),
    name: l.optional(l.string()),
  }),
)

export { location }
