/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'org.openassociation.agreementBundle'

export { $nsid }

/** A grouping of agreements to bundle detailed line item reciprocity. */
type Main = {
  $type: 'org.openassociation.agreementBundle'

  /**
   * The date, and time if desired, the information was agreed to or recorded.
   */
  created?: l.DatetimeString

  /**
   * An informal or formal textual identifier for an object. Does not imply uniqueness.
   */
  name?: string

  /**
   * Any useful textual information related to the item.
   */
  note?: string

  /**
   * All the agreements included in this agreement bundle.
   */
  bundles?: l.AtUriString[]
}

export type { Main }

/** A grouping of agreements to bundle detailed line item reciprocity. */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    created: l.optional(l.string({ format: 'datetime' })),
    name: l.optional(l.string({ maxGraphemes: 640 })),
    note: l.optional(l.string({ maxGraphemes: 10000 })),
    bundles: l.optional(l.array(l.string({ format: 'at-uri' }))),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
