/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'org.openassociation.commitment'

export { $nsid }

/** A planned economic flow that has been scheduled or promised by one agent to another agent. */
type Main = {
  $type: 'org.openassociation.commitment'

  /**
   * Defines the kind of flow, such as consume, produce, work, transfer, etc.
   */
  action:
    | 'accept'
    | 'cite'
    | 'combine'
    | 'consume'
    | 'copy'
    | 'deliverService'
    | 'dropoff'
    | 'lower'
    | 'modify'
    | 'move'
    | 'pickup'
    | 'produce'
    | 'raise'
    | 'separate'
    | 'transfer'
    | 'transferAllRights'
    | 'transferCustody'
    | 'use'
    | 'work'
    | l.UnknownString

  /**
   * Relates an input flow to its process.
   */
  inputOf?: l.AtUriString

  /**
   * Relates an output flow to its process.
   */
  outputOf?: l.AtUriString

  /**
   * The process with its inputs and outputs, or the non-process commitment or intent, is part of the plan.
   */
  plannedWithin?: l.AtUriString

  /**
   * This plan is the way this commitment or intent will be realized.
   */
  independentDemandOf?: l.AtUriString

  /**
   * Economic resource involved in the flow.
   */
  resourceInventoriedAs?: l.AtUriString

  /**
   * The economic agent by whom the intended, committed, or actual economic event is initiated.
   */
  provider?: l.DidString

  /**
   * The economic agent whom the intended, committed, or actual economic event is for.
   */
  receiver?: l.DidString

  /**
   * The planned or actual beginning date, and time if desired, of a flow or process.
   */
  hasBeginning?: l.DatetimeString

  /**
   * The planned or actual ending date, and time if desired, of a flow or process.
   */
  hasEnd?: l.DatetimeString

  /**
   * The planned or actual date, and time if desired, of a flow; can be used instead of hasBeginning and hasEnd, if so, hasBeginning and hasEnd should be able to return this value.
   */
  hasPointInTime?: l.DatetimeString

  /**
   * The date, and time if desired, something is expected to be complete.
   */
  due?: l.DatetimeString

  /**
   * The amount and unit of the economic resource counted or inventoried.
   */
  resourceQuantity?: Measure

  /**
   * The amount and unit of the work or use or citation effort-based action. This is often expressed with a time unit, but also could be cycle counts or other measures of effort or usefulness.
   */
  effortQuantity?: Measure

  /**
   * The date, and time if desired, the information was agreed to or recorded.
   */
  created?: l.DatetimeString

  /**
   * Any useful textual information related to the item.
   */
  note?: string

  /**
   * The intent(s) satisfied fully or partially by an economic event or commitment.
   */
  satisfies?: l.AtUriString[]

  /**
   * The commitment or intent or process is complete or not.  This is irrespective of if the original goal has been met, and indicates simply that no more will be done.  Default false.
   */
  finished?: boolean

  /**
   * References one or more uri's for a concept in a common taxonomy or other classification scheme for purposes of categorization or grouping; or can be one or more string classifications such as tags.
   */
  resourceClassifiedAs?: string[]

  /**
   * The lowest level resource specification or definition of an existing or potential economic resource, whether one will ever be instantiated or not.
   */
  resourceConformsTo?: ResourceSpecification

  /**
   * The required stage of the desired input economic resource. References the ProcessSpecification of the last process the economic resource went through.
   */
  stage?: l.AtUriString

  /**
   * The required state of the desired input economic resource, after coming out of a test or review process.
   */
  state?: string

  /**
   * This commitment is a primary part of the agreement.
   */
  clauseOf?: l.AtUriString

  /**
   * This commitment is a reciprocal part of the agreement.
   */
  reciprocalClauseOf?: l.AtUriString
}

export type { Main }

/** A planned economic flow that has been scheduled or promised by one agent to another agent. */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    action: l.string(),
    inputOf: l.optional(l.string({ format: 'at-uri' })),
    outputOf: l.optional(l.string({ format: 'at-uri' })),
    plannedWithin: l.optional(l.string({ format: 'at-uri' })),
    independentDemandOf: l.optional(l.string({ format: 'at-uri' })),
    resourceInventoriedAs: l.optional(l.string({ format: 'at-uri' })),
    provider: l.optional(l.string({ format: 'did' })),
    receiver: l.optional(l.string({ format: 'did' })),
    hasBeginning: l.optional(l.string({ format: 'datetime' })),
    hasEnd: l.optional(l.string({ format: 'datetime' })),
    hasPointInTime: l.optional(l.string({ format: 'datetime' })),
    due: l.optional(l.string({ format: 'datetime' })),
    resourceQuantity: l.optional(l.ref<Measure>((() => measure) as any)),
    effortQuantity: l.optional(l.ref<Measure>((() => measure) as any)),
    created: l.optional(l.string({ format: 'datetime' })),
    note: l.optional(l.string({ maxGraphemes: 10000 })),
    satisfies: l.optional(l.array(l.string({ format: 'at-uri' }))),
    finished: l.optional(l.boolean()),
    resourceClassifiedAs: l.optional(l.array(l.string())),
    resourceConformsTo: l.optional(
      l.ref<ResourceSpecification>((() => resourceSpecification) as any),
    ),
    stage: l.optional(l.string({ format: 'at-uri' })),
    state: l.optional(l.string()),
    clauseOf: l.optional(l.string({ format: 'at-uri' })),
    reciprocalClauseOf: l.optional(l.string({ format: 'at-uri' })),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

/** A quantity expressed as a numeric value with a unit of measure. AT Protocol does not support floats, so the value is represented as numerator/denominator integers. */
type Measure = {
  $type?: 'org.openassociation.commitment#measure'

  /**
   * The numeric value (numerator).
   */
  hasNumericalValue: number

  /**
   * The denominator for fractional values. Default 1 if omitted.
   */
  hasDenominator?: number

  /**
   * The display label of the unit of measure (e.g. 'kilogram', 'hour').
   */
  unitLabel?: string

  /**
   * The display symbol of the unit of measure (e.g. 'kg', 'h').
   */
  unitSymbol?: string
}

export type { Measure }

/** A quantity expressed as a numeric value with a unit of measure. AT Protocol does not support floats, so the value is represented as numerator/denominator integers. */
const measure = l.typedObject<Measure>(
  $nsid,
  'measure',
  l.object({
    hasNumericalValue: l.integer(),
    hasDenominator: l.optional(l.integer()),
    unitLabel: l.optional(l.string()),
    unitSymbol: l.optional(l.string()),
  }),
)

export { measure }

type ResourceSpecification = {
  $type?: 'org.openassociation.commitment#resourceSpecification'

  /**
   * Display name of the resource specification.
   */
  name?: string

  /**
   * AT-URI link to the ResourceSpecification record.
   */
  uri?: l.AtUriString
}

export type { ResourceSpecification }

const resourceSpecification = l.typedObject<ResourceSpecification>(
  $nsid,
  'resourceSpecification',
  l.object({
    name: l.optional(l.string()),
    uri: l.optional(l.string({ format: 'at-uri' })),
  }),
)

export { resourceSpecification }
