/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'org.openassociation.economicResource'

export { $nsid }

/** Economic or environmental things (material or digital), media of exchange, which agents agree should be accounted for and which can be inventoried. */
type Main = {
  $type: 'org.openassociation.economicResource'

  /**
   * Used when an economic resource contains units also defined as separate economic resources, for example a tool kit or a package of resources for shipping.
   */
  containedIn?: l.AtUriString[]

  /**
   * An economic resource contains at least one other economic resource, for example a tool kit or package of resources for shipping.
   */
  contains?: l.AtUriString[]

  /**
   * The agent currently with primary rights and responsibilites for the economic resource. It is the agent that is associated with the accountingQuantity of the economic resource.
   */
  primaryAccountable?: l.DidString

  /**
   * The current amount and unit of the economic resource for which the agent has primary rights and responsibilities, sometimes thought of as ownership. This can be either stored or derived from economic events affecting the resource.
   */
  accountingQuantity?: Measure

  /**
   * The current amount and unit of the economic resource which is under direct control of the agent.  It may be more or less than the accounting quantity. This can be either stored or derived from economic events affecting the resource.
   */
  onhandQuantity?: Measure

  /**
   * The current physical location of an economic resource.
   */
  currentLocation?: Location

  /**
   * The current virtual place a digital economic resource is located. Usually used for documents, code, or other electronic resource.
   */
  currentVirtualLocation?: l.UriString

  /**
   * The current virtual place a currency economic resource is located, for example the address for a bank account, crypto wallet, etc., in a domain standard format.
   */
  currentCurrencyLocation?: string

  /**
   * The uri to an image relevant to the entity, such as a logo, avatar, photo, diagram, etc.
   */
  image?: l.UriString

  /**
   * A comma separated list of uri addresses to images relevant to the resource.
   */
  imageList?: l.UriString[]

  /**
   * An informal or formal textual identifier for an object. Does not imply uniqueness.
   */
  name?: string

  /**
   * Any useful textual information related to the item.
   */
  note?: string

  /**
   * Any identifier used to track a singular resource, such as a serial number or VIN.
   */
  trackingIdentifier?: string

  /**
   * The batch lot record of this resource, if it is a batch or lot resource.
   */
  ofBatchLot?: BatchLot

  /**
   * The unit used for use or work or sometimes cite actions.
   */
  unitOfEffort?: UnitOfMeasure

  /**
   * References one or more uri's for a concept in a common taxonomy or other classification scheme for purposes of categorization or grouping; or it can be one or more string classifications such as tags.
   */
  classifiedAs?: string[]

  /**
   * The primary resource specification or definition of an existing or potential economic resource.
   */
  conformsTo?: ResourceSpecification

  /**
   * The required stage of the desired input economic resource. References the ProcessSpecification of the last process the economic resource went through.
   */
  stage?: l.AtUriString

  /**
   * The required state of the desired input economic resource, after coming out of a test or review process.
   */
  state?: string
}

export type { Main }

/** Economic or environmental things (material or digital), media of exchange, which agents agree should be accounted for and which can be inventoried. */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    containedIn: l.optional(l.array(l.string({ format: 'at-uri' }))),
    contains: l.optional(l.array(l.string({ format: 'at-uri' }))),
    primaryAccountable: l.optional(l.string({ format: 'did' })),
    accountingQuantity: l.optional(l.ref<Measure>((() => measure) as any)),
    onhandQuantity: l.optional(l.ref<Measure>((() => measure) as any)),
    currentLocation: l.optional(l.ref<Location>((() => location) as any)),
    currentVirtualLocation: l.optional(l.string({ format: 'uri' })),
    currentCurrencyLocation: l.optional(l.string()),
    image: l.optional(l.string({ format: 'uri' })),
    imageList: l.optional(l.array(l.string({ format: 'uri' }))),
    name: l.optional(l.string({ maxGraphemes: 640 })),
    note: l.optional(l.string({ maxGraphemes: 10000 })),
    trackingIdentifier: l.optional(l.string()),
    ofBatchLot: l.optional(l.ref<BatchLot>((() => batchLot) as any)),
    unitOfEffort: l.optional(
      l.ref<UnitOfMeasure>((() => unitOfMeasure) as any),
    ),
    classifiedAs: l.optional(l.array(l.string())),
    conformsTo: l.optional(
      l.ref<ResourceSpecification>((() => resourceSpecification) as any),
    ),
    stage: l.optional(l.string({ format: 'at-uri' })),
    state: l.optional(l.string()),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

/** A quantity expressed as a numeric value with a unit of measure. AT Protocol does not support floats, so the value is represented as numerator/denominator integers. */
type Measure = {
  $type?: 'org.openassociation.economicResource#measure'

  /**
   * The numeric value (numerator).
   */
  hasNumericalValue: number

  /**
   * The denominator for fractional values. Default 1 if omitted.
   */
  hasDenominator?: number

  /**
   * The display label of the unit of measure (e.g. 'kilogram', 'hour').
   */
  unitLabel?: string

  /**
   * The display symbol of the unit of measure (e.g. 'kg', 'h').
   */
  unitSymbol?: string
}

export type { Measure }

/** A quantity expressed as a numeric value with a unit of measure. AT Protocol does not support floats, so the value is represented as numerator/denominator integers. */
const measure = l.typedObject<Measure>(
  $nsid,
  'measure',
  l.object({
    hasNumericalValue: l.integer(),
    hasDenominator: l.optional(l.integer()),
    unitLabel: l.optional(l.string()),
    unitSymbol: l.optional(l.string()),
  }),
)

export { measure }

type Location = {
  $type?: 'org.openassociation.economicResource#location'

  /**
   * WGS84 latitude (decimal degrees).
   */
  lat?: string

  /**
   * WGS84 longitude (decimal degrees).
   */
  long?: string

  /**
   * WGS84 altitude (decimal meters above the local reference ellipsoid).
   */
  alt?: string

  /**
   * A textual address that can be mapped using mapping software.
   */
  mappableAddress?: string

  /**
   * An informal or formal textual identifier for the location.
   */
  name?: string
}

export type { Location }

const location = l.typedObject<Location>(
  $nsid,
  'location',
  l.object({
    lat: l.optional(l.string()),
    long: l.optional(l.string()),
    alt: l.optional(l.string()),
    mappableAddress: l.optional(l.string()),
    name: l.optional(l.string()),
  }),
)

export { location }

type BatchLot = {
  $type?: 'org.openassociation.economicResource#batchLot'

  /**
   * The code or identifier for this batch or lot.
   */
  batchLotCode?: string

  /**
   * The date after which the resource should no longer be used or consumed.
   */
  expirationDate?: l.DatetimeString
}

export type { BatchLot }

const batchLot = l.typedObject<BatchLot>(
  $nsid,
  'batchLot',
  l.object({
    batchLotCode: l.optional(l.string()),
    expirationDate: l.optional(l.string({ format: 'datetime' })),
  }),
)

export { batchLot }

type UnitOfMeasure = {
  $type?: 'org.openassociation.economicResource#unitOfMeasure'

  /**
   * The display label of the unit (e.g. 'kilogram', 'hour').
   */
  unitLabel?: string

  /**
   * The display symbol of the unit (e.g. 'kg', 'h').
   */
  unitSymbol?: string
}

export type { UnitOfMeasure }

const unitOfMeasure = l.typedObject<UnitOfMeasure>(
  $nsid,
  'unitOfMeasure',
  l.object({
    unitLabel: l.optional(l.string()),
    unitSymbol: l.optional(l.string()),
  }),
)

export { unitOfMeasure }

type ResourceSpecification = {
  $type?: 'org.openassociation.economicResource#resourceSpecification'

  /**
   * Display name of the resource specification.
   */
  name?: string

  /**
   * AT-URI link to the ResourceSpecification record.
   */
  uri?: l.AtUriString
}

export type { ResourceSpecification }

const resourceSpecification = l.typedObject<ResourceSpecification>(
  $nsid,
  'resourceSpecification',
  l.object({
    name: l.optional(l.string()),
    uri: l.optional(l.string({ format: 'at-uri' })),
  }),
)

export { resourceSpecification }
