/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as OpenassociationRecipe from './recipe.defs.js'

const $nsid = 'org.openassociation.listRecipes'

export { $nsid }

/** List recipes. Filterable by: primaryOutput, recipeIncludes. */
const main = l.query(
  $nsid,
  l.params({
    uri: l.optional(l.string({ format: 'at-uri' })),
    primaryOutput: l.optional(l.string({ format: 'at-uri' })),
    recipeIncludes: l.optional(l.string({ format: 'at-uri' })),
    limit: l.optional(
      l.withDefault(l.integer({ minimum: 1, maximum: 100 }), 50),
    ),
    cursor: l.optional(l.string()),
  }),
  l.jsonPayload({
    records: l.array(l.ref<RecordItem>((() => recordItem) as any)),
    cursor: l.optional(l.string()),
  }),
)
export { main }

export type Params = l.InferMethodParams<typeof main>
export type Output = l.InferMethodOutput<typeof main>
export type OutputBody = l.InferMethodOutputBody<typeof main>

export const $lxm = main.nsid,
  $params = main.parameters,
  $output = main.output

type RecordItem = {
  $type?: 'org.openassociation.listRecipes#recordItem'

  /**
   * AT-URI of the record.
   */
  uri: l.AtUriString

  /**
   * The full record value.
   */
  value?: OpenassociationRecipe.Main
}

export type { RecordItem }

const recordItem = l.typedObject<RecordItem>(
  $nsid,
  'recordItem',
  l.object({
    uri: l.string({ format: 'at-uri' }),
    value: l.optional(
      l.ref<OpenassociationRecipe.Main>(
        (() => OpenassociationRecipe.main) as any,
      ),
    ),
  }),
)

export { recordItem }
