/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as OpenassociationEconomicEvent from './economicEvent.defs.js'

const $nsid = 'org.openassociation.listEconomicEvents'

export { $nsid }

/** List economicEvents. Filterable by: action, inputOf, outputOf, resourceInventoriedAs, toResourceInventoriedAs, provider, receiver, corrects, settles, fulfills, satisfies, realizationOf, reciprocalRealizationOf. */
const main = l.query(
  $nsid,
  l.params({
    uri: l.optional(l.string({ format: 'at-uri' })),
    action: l.optional(l.string()),
    inputOf: l.optional(l.string({ format: 'at-uri' })),
    outputOf: l.optional(l.string({ format: 'at-uri' })),
    resourceInventoriedAs: l.optional(l.string({ format: 'at-uri' })),
    toResourceInventoriedAs: l.optional(l.string({ format: 'at-uri' })),
    provider: l.optional(l.string({ format: 'did' })),
    receiver: l.optional(l.string({ format: 'did' })),
    corrects: l.optional(l.string({ format: 'at-uri' })),
    settles: l.optional(l.string({ format: 'at-uri' })),
    fulfills: l.optional(l.string({ format: 'at-uri' })),
    satisfies: l.optional(l.string({ format: 'at-uri' })),
    realizationOf: l.optional(l.string({ format: 'at-uri' })),
    reciprocalRealizationOf: l.optional(l.string({ format: 'at-uri' })),
    limit: l.optional(
      l.withDefault(l.integer({ minimum: 1, maximum: 100 }), 50),
    ),
    cursor: l.optional(l.string()),
  }),
  l.jsonPayload({
    records: l.array(l.ref<RecordItem>((() => recordItem) as any)),
    cursor: l.optional(l.string()),
  }),
)
export { main }

export type Params = l.InferMethodParams<typeof main>
export type Output = l.InferMethodOutput<typeof main>
export type OutputBody = l.InferMethodOutputBody<typeof main>

export const $lxm = main.nsid,
  $params = main.parameters,
  $output = main.output

type RecordItem = {
  $type?: 'org.openassociation.listEconomicEvents#recordItem'

  /**
   * AT-URI of the record.
   */
  uri: l.AtUriString

  /**
   * The full record value.
   */
  value?: OpenassociationEconomicEvent.Main
}

export type { RecordItem }

const recordItem = l.typedObject<RecordItem>(
  $nsid,
  'recordItem',
  l.object({
    uri: l.string({ format: 'at-uri' }),
    value: l.optional(
      l.ref<OpenassociationEconomicEvent.Main>(
        (() => OpenassociationEconomicEvent.main) as any,
      ),
    ),
  }),
)

export { recordItem }
