/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as OpenassociationRecipeExchange from './recipeExchange.defs.js'

const $nsid = 'org.openassociation.listRecipeExchanges'

export { $nsid }

/** List recipeExchanges. Filterable by: recipeStipulates, recipeStipulatesReciprocal. */
const main = l.query(
  $nsid,
  l.params({
    uri: l.optional(l.string({ format: 'at-uri' })),
    recipeStipulates: l.optional(l.string({ format: 'at-uri' })),
    recipeStipulatesReciprocal: l.optional(l.string({ format: 'at-uri' })),
    limit: l.optional(
      l.withDefault(l.integer({ minimum: 1, maximum: 100 }), 50),
    ),
    cursor: l.optional(l.string()),
  }),
  l.jsonPayload({
    records: l.array(l.ref<RecordItem>((() => recordItem) as any)),
    cursor: l.optional(l.string()),
  }),
)
export { main }

export type Params = l.InferMethodParams<typeof main>
export type Output = l.InferMethodOutput<typeof main>
export type OutputBody = l.InferMethodOutputBody<typeof main>

export const $lxm = main.nsid,
  $params = main.parameters,
  $output = main.output

type RecordItem = {
  $type?: 'org.openassociation.listRecipeExchanges#recordItem'

  /**
   * AT-URI of the record.
   */
  uri: l.AtUriString

  /**
   * The full record value.
   */
  value?: OpenassociationRecipeExchange.Main
}

export type { RecordItem }

const recordItem = l.typedObject<RecordItem>(
  $nsid,
  'recordItem',
  l.object({
    uri: l.string({ format: 'at-uri' }),
    value: l.optional(
      l.ref<OpenassociationRecipeExchange.Main>(
        (() => OpenassociationRecipeExchange.main) as any,
      ),
    ),
  }),
)

export { recordItem }
