/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'org.openassociation.plan'

export { $nsid }

/** A logical collection of processes, with optional connected agreements, that constitute a body of scheduled work with defined deliverable(s). */
type Main = {
  $type: 'org.openassociation.plan'

  /**
   * The processes and and non-process commitments/intents that constitute the plan.
   */
  planIncludes?: l.AtUriString[]

  /**
   * The commitments and/or intents which this plan was created to deliver.
   */
  hasIndependentDemand?: l.AtUriString[]

  /**
   * The date, and time if desired, something is expected to be complete.
   */
  due?: l.DatetimeString

  /**
   * The date, and time if desired, the information was agreed to or recorded.
   */
  created?: l.DatetimeString

  /**
   * An informal or formal textual identifier for an object. Does not imply uniqueness.
   */
  name?: string

  /**
   * Any useful textual information related to the item.
   */
  note?: string
}

export type { Main }

/** A logical collection of processes, with optional connected agreements, that constitute a body of scheduled work with defined deliverable(s). */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    planIncludes: l.optional(l.array(l.string({ format: 'at-uri' }))),
    hasIndependentDemand: l.optional(l.array(l.string({ format: 'at-uri' }))),
    due: l.optional(l.string({ format: 'datetime' })),
    created: l.optional(l.string({ format: 'datetime' })),
    name: l.optional(l.string({ maxGraphemes: 640 })),
    note: l.optional(l.string({ maxGraphemes: 10000 })),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
