/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'org.openassociation.recipeExchange'

export { $nsid }

/** Specifies an exchange type agreement as part of a recipe. */
type Main = {
  $type: 'org.openassociation.recipeExchange'

  /**
   * All the primary clauses of a recipe exchange.
   */
  recipeStipulates?: l.AtUriString[]

  /**
   * All the reciprocal clauses of a recipe exchange.
   */
  recipeStipulatesReciprocal?: l.AtUriString[]

  /**
   * An informal or formal textual identifier for an object. Does not imply uniqueness.
   */
  name?: string

  /**
   * Any useful textual information related to the item.
   */
  note?: string
}

export type { Main }

/** Specifies an exchange type agreement as part of a recipe. */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    recipeStipulates: l.optional(l.array(l.string({ format: 'at-uri' }))),
    recipeStipulatesReciprocal: l.optional(
      l.array(l.string({ format: 'at-uri' })),
    ),
    name: l.optional(l.string({ maxGraphemes: 640 })),
    note: l.optional(l.string({ maxGraphemes: 10000 })),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
