/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'org.openassociation.resourceSpecification'

export { $nsid }

/** Specifies the kind of economic or environmental resource, even if the resource is not instantiated as an EconomicResource. Could define a material or digital thing, service, medium of exchange or currency, skill or type of work. */
type Main = {
  $type: 'org.openassociation.resourceSpecification'

  /**
   * The uri to an image relevant to the entity, such as a logo, avatar, photo, diagram, etc.
   */
  image?: l.UriString

  /**
   * A comma separated list of uri addresses to images relevant to the resource.
   */
  imageList?: l.UriString[]

  /**
   * An informal or formal textual identifier for an object. Does not imply uniqueness.
   */
  name?: string

  /**
   * Any useful textual information related to the item.
   */
  note?: string

  /**
   * True if the resource is a currency, money, token, credit, etc. used as a medium of exchange.
   */
  mediumOfExchange?: boolean

  /**
   * Defines if any resource of that type can be freely substituted for any other resource of that type when used, consumed, traded, etc.
   */
  substitutable?: boolean

  /**
   * The default unit used for use or work.
   */
  defaultUnitOfEffort?: UnitOfMeasure

  /**
   * The default unit used for the resource itself.
   */
  defaultUnitOfResource?: UnitOfMeasure

  /**
   * References one or more uri's for a concept in a common taxonomy or other classification scheme for purposes of categorization or grouping; or can be one or more string classifications such as tags.
   */
  resourceClassifiedAs?: string[]
}

export type { Main }

/** Specifies the kind of economic or environmental resource, even if the resource is not instantiated as an EconomicResource. Could define a material or digital thing, service, medium of exchange or currency, skill or type of work. */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    image: l.optional(l.string({ format: 'uri' })),
    imageList: l.optional(l.array(l.string({ format: 'uri' }))),
    name: l.optional(l.string({ maxGraphemes: 640 })),
    note: l.optional(l.string({ maxGraphemes: 10000 })),
    mediumOfExchange: l.optional(l.boolean()),
    substitutable: l.optional(l.boolean()),
    defaultUnitOfEffort: l.optional(
      l.ref<UnitOfMeasure>((() => unitOfMeasure) as any),
    ),
    defaultUnitOfResource: l.optional(
      l.ref<UnitOfMeasure>((() => unitOfMeasure) as any),
    ),
    resourceClassifiedAs: l.optional(l.array(l.string())),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

type UnitOfMeasure = {
  $type?: 'org.openassociation.resourceSpecification#unitOfMeasure'

  /**
   * The display label of the unit (e.g. 'kilogram', 'hour').
   */
  unitLabel?: string

  /**
   * The display symbol of the unit (e.g. 'kg', 'h').
   */
  unitSymbol?: string
}

export type { UnitOfMeasure }

const unitOfMeasure = l.typedObject<UnitOfMeasure>(
  $nsid,
  'unitOfMeasure',
  l.object({
    unitLabel: l.optional(l.string()),
    unitSymbol: l.optional(l.string()),
  }),
)

export { unitOfMeasure }
